//
//  Workspace.swift
//  AppManifests
//
//  Created by Qcells.
//  Copyright © 2025 QCells. All rights reserved.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: ProjectInfo.appName,
    projects: ["Projects/**"],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
